import type { Topico, Questao, EstadoTopico } from './types'

export const TOPICOS_MOCK: Topico[] = [
  {
    id: 'mat.numeros.reais',
    titulo: 'Números Reais',
    descricao: 'Conjuntos numéricos, operações e propriedades',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 1,
    pre_requisitos: [],
  },
  {
    id: 'mat.algebra.equacoes1',
    titulo: 'Equações do 1.º Grau',
    descricao: 'Equações lineares e sistemas',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 2,
    pre_requisitos: ['mat.numeros.reais'],
  },
  {
    id: 'mat.algebra.equacoes2',
    titulo: 'Equações do 2.º Grau',
    descricao: 'Fórmula de Bhaskara, discriminante e relações de Girard',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 2,
    pre_requisitos: ['mat.algebra.equacoes1'],
  },
  {
    id: 'mat.funcoes.linear',
    titulo: 'Funções Lineares e Afins',
    descricao: 'Função afim, gráfico, taxa de variação',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 2,
    pre_requisitos: ['mat.numeros.reais'],
  },
  {
    id: 'mat.funcoes.quadratica',
    titulo: 'Funções Quadráticas',
    descricao: 'Parábola, vértice, zeros e sinal',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 3,
    pre_requisitos: ['mat.funcoes.linear', 'mat.algebra.equacoes2'],
  },
  {
    id: 'mat.probabilidade',
    titulo: 'Probabilidade',
    descricao: 'Espaço amostral, eventos, probabilidade condicional',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 3,
    pre_requisitos: ['mat.combinatoria'],
  },
  {
    id: 'mat.combinatoria',
    titulo: 'Análise Combinatória',
    descricao: 'Princípio multiplicativo, permutação, combinação',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 3,
    pre_requisitos: ['mat.numeros.reais'],
  },
  {
    id: 'mat.estatistica',
    titulo: 'Estatística Básica',
    descricao: 'Média, mediana, moda, gráficos e tabelas',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 2,
    pre_requisitos: ['mat.numeros.reais'],
  },
  {
    id: 'mat.geometria.plana.areas',
    titulo: 'Áreas de Figuras Planas',
    descricao: 'Triângulo, quadriláteros, círculo e figuras compostas',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 2,
    pre_requisitos: ['mat.geometria.plana.basico'],
  },
  {
    id: 'mat.geometria.plana.basico',
    titulo: 'Geometria Plana — Fundamentos',
    descricao: 'Ângulos, polígonos, perímetro',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 1,
    pre_requisitos: [],
  },
  {
    id: 'mat.financeira',
    titulo: 'Matemática Financeira',
    descricao: 'Juros simples e compostos, porcentagem, desconto',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 3,
    pre_requisitos: ['mat.funcoes.exponencial'],
  },
  {
    id: 'mat.funcoes.exponencial',
    titulo: 'Funções Exponenciais',
    descricao: 'Base, expoente, crescimento e decrescimento exponencial',
    area: 'matematica',
    disciplina: 'matemática',
    nivel: 3,
    pre_requisitos: ['mat.funcoes.linear'],
  },
  // ── Química ──
  {
    id: 'qui.solucoes',
    titulo: 'Soluções e Diluição',
    descricao: 'Concentração, solubilidade e a lei C₁V₁ = C₂V₂',
    area: 'quimica',
    disciplina: 'química',
    nivel: 2,
    pre_requisitos: [],
  },
  {
    id: 'qui.estequiometria',
    titulo: 'Estequiometria',
    descricao: 'Relações de mol, massa e volumes em reações químicas',
    area: 'quimica',
    disciplina: 'química',
    nivel: 3,
    pre_requisitos: ['qui.solucoes'],
  },
]

// Real ENEM questions (pure text, no images needed)
export const QUESTOES_MOCK: (Questao & { _gabarito: string })[] = [
  {
    id: 'ENEM-2009-141',
    id_origem: 'ENEM-2009-141',
    prova: 'ENEM',
    ano: 2009,
    numero_original: '141',
    area_origem: 'matematica',
    tipo: 'objetiva',
    enunciado:
      'Uma resolução do Conselho Nacional de Política Energética (CNPE) estabeleceu a obrigatoriedade de adição de biodiesel ao óleo diesel comercializado nos postos. A exigência é que, a partir de 1.º de julho de 2009, 4% do volume da mistura final seja formada por biodiesel. Até junho de 2009, esse percentual era de 3%.\n\nEstimativas indicam que, com a adição de 4% de biodiesel ao dísel, serão consumidos 925 milhões de litros de biodiesel no segundo semestre de 2009. Considerando-se essa estimativa, para o mesmo volume da mistura final dísel/biodiesel consumida no segundo semestre de 2009, qual seria o consumo de biodiesel com a adição de 3%?',
    alternativas: {
      A: '27,75 milhões de litros.',
      B: '37,00 milhões de litros.',
      C: '231,25 milhões de litros.',
      D: '693,75 milhões de litros.',
      E: '888,00 milhões de litros.',
    },
    _gabarito: 'D',
    topico_id: 'mat.estatistica',
    imagens_locais: null,
  },
  {
    id: 'ENEM-2009-145',
    id_origem: 'ENEM-2009-145',
    prova: 'ENEM',
    ano: 2009,
    numero_original: '145',
    area_origem: 'matematica',
    tipo: 'objetiva',
    enunciado:
      'O controle de qualidade de uma empresa fabricante de telefones celulares aponta que a probabilidade de um aparelho de determinado modelo apresentar defeito de fabricação é de 0,2%. Se uma loja acaba de vender 4 aparelhos desse modelo para um cliente, qual é a probabilidade de esse cliente sair da loja com exatamente dois aparelhos defeituosos?',
    alternativas: {
      A: '2 × (0,2%)⁴',
      B: '4 × (0,2%)²',
      C: '6 × (0,2%)² × (99,8%)²',
      D: '4 × (0,2%)',
      E: '6 × (0,2%) × (99,8%)',
    },
    _gabarito: 'C',
    topico_id: 'mat.probabilidade',
    imagens_locais: null,
  },
  {
    id: 'ENEM-2009-151',
    id_origem: 'ENEM-2009-151',
    prova: 'ENEM',
    ano: 2009,
    numero_original: '151',
    area_origem: 'matematica',
    tipo: 'objetiva',
    enunciado:
      'Um grupo de 50 pessoas fez um orçamento inicial para organizar uma festa, que seria dividido entre elas em cotas iguais. Verificou-se ao final que, para arcar com todas as despesas, faltavam R$ 510,00, e que 5 novas pessoas haviam ingressado no grupo. No acerto foi decidido que a despesa total seria dividida em partes iguais pelas 55 pessoas. Quem não havia ainda contribuído pagaria a sua parte, e cada uma das 50 pessoas do grupo inicial deveria contribuir com mais R$ 7,00.\n\nDe acordo com essas informações, qual foi o valor da cota calculada no acerto final para cada uma das 55 pessoas?',
    alternativas: {
      A: 'R$ 14,00.',
      B: 'R$ 17,00.',
      C: 'R$ 22,00.',
      D: 'R$ 32,00.',
      E: 'R$ 57,00.',
    },
    _gabarito: 'D',
    topico_id: 'mat.algebra.equacoes1',
    imagens_locais: null,
  },
  {
    id: 'ENEM-2009-154',
    id_origem: 'ENEM-2009-154',
    prova: 'ENEM',
    ano: 2009,
    numero_original: '154',
    area_origem: 'matematica',
    tipo: 'objetiva',
    enunciado:
      'A rampa de um hospital tem na sua parte mais elevada uma altura de 2,2 metros. Um paciente ao caminhar sobre a rampa percebe que se deslocou 3,2 metros e alcançou uma altura de 0,8 metro.\n\nA distância em metros que o paciente ainda deve caminhar para atingir o ponto mais alto da rampa é',
    alternativas: {
      A: '1,16 metros.',
      B: '3,0 metros.',
      C: '5,4 metros.',
      D: '5,6 metros.',
      E: '7,04 metros.',
    },
    _gabarito: 'D',
    topico_id: 'mat.geometria.plana.basico',
    imagens_locais: null,
  },
  {
    id: 'ENEM-2009-155',
    id_origem: 'ENEM-2009-155',
    prova: 'ENEM',
    ano: 2009,
    numero_original: '155',
    area_origem: 'matematica',
    tipo: 'objetiva',
    enunciado:
      'Um posto de combustível vende 10.000 litros de álcool por dia a R$ 1,50 cada litro. Seu proprietário percebeu que, para cada centavo de desconto que concedia por litro, eram vendidos 100 litros a mais por dia. Por exemplo, no dia em que o preço do álcool foi R$ 1,48, foram vendidos 10.200 litros.\n\nConsiderando x o valor, em centavos, do desconto dado no preço de cada litro, e V o valor, em R$, arrecadado por dia com a venda do álcool, então a expressão que relaciona V e x é',
    alternativas: {
      A: 'V = 10.000 + 50x – x²',
      B: 'V = 10.000 + 50x + x²',
      C: 'V = 15.000 – 50x – x²',
      D: 'V = 15.000 + 50x – x²',
      E: 'V = 15.000 – 50x + x²',
    },
    _gabarito: 'D',
    topico_id: 'mat.funcoes.quadratica',
    imagens_locais: null,
  },
  {
    id: 'ENEM-2009-161',
    id_origem: 'ENEM-2009-161',
    prova: 'ENEM',
    ano: 2009,
    numero_original: '161',
    area_origem: 'matematica',
    tipo: 'objetiva',
    enunciado:
      'Suponha que a etapa final de uma gincana escolar consista em um desafio de conhecimentos. Cada equipe escolheria 10 alunos para realizar uma prova objetiva, e a pontuação da equipe seria dada pela mediana das notas obtidas pelos alunos. As provas valiam, no máximo, 10 pontos cada. Ao final, a vencedora foi a equipe Ômega, com 7,8 pontos, seguida pela equipe Delta, com 7,6 pontos. Um dos alunos da equipe Gama, a qual ficou na terceira e última colocação, não pôde comparecer, tendo recebido nota zero na prova. As notas obtidas pelos 10 alunos da equipe Gama foram 10; 6,5; 8; 10; 7; 6,5; 7; 8; 6; 0.\n\nSe o aluno da equipe Gama que faltou tivesse comparecido, essa equipe',
    alternativas: {
      A: 'Teria a pontuação igual a 6,5 se ele obtivesse nota 0.',
      B: 'Seria a vencedora se ele obtivesse nota 10.',
      C: 'Seria a segunda colocada se ele obtivesse nota 8.',
      D: 'Permaneceria na terceira posição, independentemente da nota obtida pelo aluno.',
      E: 'Empataria com a equipe Ômega na primeira colocação se o aluno obtivesse nota 9.',
    },
    _gabarito: 'D',
    topico_id: 'mat.estatistica',
    imagens_locais: null,
  },
  {
    id: 'ENEM-2009-162',
    id_origem: 'ENEM-2009-162',
    prova: 'ENEM',
    ano: 2009,
    numero_original: '162',
    area_origem: 'matematica',
    tipo: 'objetiva',
    enunciado:
      'Uma escola lançou uma campanha para seus alunos arrecadarem, durante 30 dias, alimentos não perecíveis para doar a uma comunidade carente da região. Vinte alunos aceitaram a tarefa e nos primeiros 10 dias trabalharam 3 horas diárias, arrecadando 12 kg de alimentos por dia. Animados com os resultados, 30 novos alunos somaram-se ao grupo, e passaram a trabalhar 4 horas por dia nos dias seguintes até o término da campanha.\n\nAdmitindo-se que o ritmo de coleta tenha se mantido constante, a quantidade de alimentos arrecadados ao final do prazo estipulado seria de',
    alternativas: {
      A: '920 kg.',
      B: '800 kg.',
      C: '720 kg.',
      D: '600 kg.',
      E: '570 kg.',
    },
    _gabarito: 'A',
    topico_id: 'mat.algebra.equacoes1',
    imagens_locais: null,
  },
]

export function estadoTopicosInicial(): EstadoTopico[] {
  return TOPICOS_MOCK.map((t) => ({
    topico_id: t.id,
    status: 'nao_iniciado',
    mastery_score: 0,
    decay_score: 0,
    total_tentativas: 0,
    questoes_unicas_tentadas: 0,
    questoes_unicas_acertadas: 0,
    ultima_tentativa_em: null,
  }))
}
